'use client';
import { useEffect,useState } from 'react';
import { Moon,Play,SlidersHorizontal,MessageSquare,MapPin,Brain,Clock,Loader2,Eye,Radio,Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { locations,timeLabel,pendingInterventions,type World,type Character } from '@/lib/world';
import PixelWorld,{PixelSprite} from '@/components/pixel-world';
function Picker({value,onChange,items,label,disabled=false}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string;disabled?:boolean}){return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger className="picker" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>;}
function Initial({c,small=false}:{c:Character;small?:boolean}){return <span className={`initial ${small?'small':''}`} style={{color:c.color,borderColor:c.color+'55',background:c.color+'14'}}><PixelSprite id={c.id}/></span>;}
export default function WorldApp({signInPath,displayName}:{signInPath:string;displayName:string}){
const [world,setWorld]=useState<World|null>(null),[selected,setSelected]=useState('cass'),[busy,setBusy]=useState(false),[error,setError]=useState('');
const [mode,setMode]=useState('demo'),[key,setKey]=useState(''),[model,setModel]=useState(''),[settings,setSettings]=useState(false),[minutes,setMinutes]=useState('30'),[target,setTarget]=useState('cass'),[text,setText]=useState(''),[notice,setNotice]=useState(''),[signInRequired,setSignInRequired]=useState(false),[playing,setPlaying]=useState(false);
async function refresh(){setBusy(true);setError('');try{const r=await fetch('/api/world',{credentials:'same-origin'});const d=await r.json() as {world:World;error?:string;signInRequired?:boolean};if(!r.ok){if(r.status===401)setSignInRequired(true);throw Error(d.error);}setSignInRequired(false);setWorld(d.world);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
useEffect(()=>{void refresh();},[]);
async function act(operation:string){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/world',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation,minutes:Number(minutes),mode,key:mode!=='demo'?key:undefined,model:mode!=='demo'?model:undefined,target,text})});const d=await r.json() as {world:World;error?:string;signInRequired?:boolean};if(!r.ok){if(r.status===401)setSignInRequired(true);throw Error(d.error);}setSignInRequired(false);setWorld(d.world);if(operation==='intervene')setText('');setNotice(operation==='advance'?'回合已儲存':`${target==='all'?'所有角色':world?.characters.find(c=>c.id===target)?.name||'角色'} 已收到；再推進一次時間，會做出行動或回覆。`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
function selectCharacter(id:string){setSelected(id);setTarget(id);}
const character=world?.characters.find(c=>c.id===selected);
const pending=world&&character?pendingInterventions(world,character):[];
return <main><header className="topbar"><a href="/" className="brand"><span className="brand-mark"><Moon size={21}/></span><span>Quiet Hours<small>NPC 觀察室</small></span></a><div className="header-right"><span className="edition">{displayName} · 已登入</span><Button variant="outline" className="settings-button" onClick={()=>setSettings(!settings)} aria-expanded={settings}><SlidersHorizontal size={16}/>模型設定</Button></div></header>
{settings&&<section className="settings panel"><div><h2>決策方式</h2><p>規則模式可以直接試玩。AI 模式每回合呼叫模型 3 次。OpenAI 直連使用你的 API 額度，與 ChatGPT 訂閱分開計費。</p></div><div className="settings-fields"><label>模式<Picker label="決策方式" value={mode} onChange={v=>{setMode(v);setKey('');setModel(v==='openai'?'gpt-6-luna':'');}} disabled={busy} items={[{value:'demo',label:'規則試玩'},{value:'openai',label:'OpenAI 直連'},{value:'ai',label:'OpenRouter AI'}]}/></label><label>模型{mode==='openai'?<Picker label="OpenAI 模型" value={model} onChange={setModel} disabled={busy} items={[{value:'gpt-6-luna',label:'GPT-6 Luna · 推薦'},{value:'gpt-6.1-sol',label:'GPT-6.1 Sol'}]}/>:<input value={model} onChange={e=>setModel(e.target.value)} placeholder="供應商／模型名稱" autoComplete="off" disabled={busy}/>}</label><label>{mode==='openai'?'OpenAI':'OpenRouter'} API Key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="貼上你的 API Key" autoComplete="off"/></label></div><p className="settings-note">Key 僅保留在本次頁面記憶體，送到後端用於模型請求；不寫入世界紀錄。重新整理後需重填。<a href={mode==='openai'?'https://platform.openai.com/api-keys':'https://openrouter.ai/settings/keys'} target="_blank" rel="noreferrer">取得 API Key</a></p></section>}
<section className="world-toolbar"><div><div className="eyebrow">世界時間 · DAY {world?Math.floor(world.minute/1440)+1:'01'}</div><div className="clock">{world?timeLabel(world.minute):'21:00'}<span>夜色裡，生活繼續。</span></div></div><div className="advance"><span className={`mode-label ${mode!=='demo'?'ai':''}`}><Radio size={14}/>{mode==='openai'?'GPT 決策':mode==='ai'?'AI 決策':'規則試玩'}</span><Picker label="推進時間間隔" value={minutes} onChange={setMinutes} disabled={busy} items={[{value:'15',label:'15 分鐘'},{value:'30',label:'30 分鐘'}]}/><Button className="advance-button" disabled={busy||playing||!world||(mode!=='demo'&&(!key.trim()||!model.trim()))} onClick={()=>act('advance')}>{busy?<Loader2 className="spin" size={17}/>:<Play size={16}/>} {busy?'處理中…':playing?'角色行動中…':'推進時間'}</Button></div></section>
<div className="feedback" aria-live="polite">{error?<div className="error" role="alert">{error}<Button variant="ghost" onClick={refresh} disabled={busy}>重新載入</Button>{signInRequired&&<a href={signInPath} target="_top" className="auth-retry">用 ChatGPT 重新登入</a>}</div>:notice?<span><Check size={14}/>{notice}</span>:<span>手動推進時間。每位角色每回合選擇一個行動；關閉網頁時，世界暫停。</span>}</div>
{!world?<section className="panel loading"><Loader2 className={busy?'spin':''}/><p>{busy?'正在讀取你的世界…':'世界尚未載入'}</p></section>:<div className="workspace"><div className="main-column"><section className="world-view panel"><div className="section-head"><h1>此刻的世界</h1><span><Eye size={15}/>觀察者視角</span></div><PixelWorld world={world} selected={selected} onSelect={selectCharacter} onPlayingChange={setPlaying}/><div className="world-footer"><span>03 個角色 · 03 個地點</span><span><Clock size={14}/>已走過 {world.turn} 個回合</span></div></section>
<section className="feed panel"><div className="section-head"><h2>生活紀錄</h2><span>最近 300 則 · 由新到舊</span></div><div className="event-list">{[...world.events].reverse().map(event=>{const c=world.characters.find(x=>x.id===event.actor);return <article className="event" key={event.id}><time><small>D{Math.floor(event.time/1440)+1}</small>{timeLabel(event.time)}</time><span className="event-marker" style={{background:c?.color||'#98a4b7'}}/><div><div className="event-meta"><b style={{color:c?.color}}>{c?.name||(event.actor==='observer'?'觀察者':'世界')}</b><span>{event.kind==='say'&&event.scene?.target==='observer'?'回覆你':event.kind==='reflect'?'私密想法':event.kind==='message'?'私人訊息':event.kind==='blocked'?'規則攔截':event.kind==='intervention'?'介入事件':'生活片段'}</span></div><p>{event.text}</p><small className="audience">知情：{event.audience.map(id=>world.characters.find(x=>x.id===id)?.name).join('、')||'無'}</small></div></article>})}</div></section></div>
<aside className="side-column"><section className="character panel"><div className="section-head"><h2>角色狀態</h2><Brain size={17}/></div><div className="character-picker">{world.characters.map(c=><button key={c.id} onClick={()=>selectCharacter(c.id)} className={selected===c.id?'active':''} aria-pressed={selected===c.id}>{c.name}</button>)}</div>{character&&<><div className="identity"><Initial c={character}/><div><h2>{character.name}</h2><span><MapPin size={13}/>{locations.find(l=>l.id===character.location)?.name}</span></div><span className="mood" style={{color:character.color}}>{character.mood}</span></div><p className="activity">{character.activity}</p>{pending.length>0&&<div className="pending-request"><h3>等待下一回合回應</h3><p>{pending.at(-1)?.text}</p></div>}<div className="detail"><h3>現在想做的事</h3><p>{character.goal}</p></div><div className="detail"><h3>性格</h3><p>{character.personality}</p></div><div className="detail relations"><h3>關係</h3>{Object.entries(character.relationships).map(([id,t])=><p key={id}><b>{world.characters.find(x=>x.id===id)?.name}</b>{t}</p>)}</div><div className="detail"><h3>自己的記憶 <span>{character.memories.length} / 80</span></h3><div className="memories">{[...character.memories].reverse().map((m,i)=><div key={`${m.time}-${i}`}><time>D{Math.floor(m.time/1440)+1} · {timeLabel(m.time)}</time><p>{m.text}</p></div>)}</div></div></>}</section>
<section className="intervene panel"><div className="section-head"><h2>輕輕介入</h2><MessageSquare size={17}/></div><form onSubmit={e=>{e.preventDefault();void act('intervene');}}><label>誰會知道？<Picker label="事件知情對象" value={target} onChange={setTarget} disabled={busy} items={[...world.characters.map(c=>({value:c.id,label:`只對 ${c.name} 說`})),{value:'all',label:'所有人的共同事件'}]}/></label><label htmlFor="intervention">你想說的話或發生的事</label><textarea id="intervention" value={text} onChange={e=>setText(e.target.value)} placeholder="例如：咖啡館明天下午有一場小型手作活動。" maxLength={500} rows={3}/><div className="intervene-bottom"><span>{text.length} / 500</span><Button type="submit" variant="outline" disabled={busy||playing||!text.trim()}>加入事件</Button></div><p className="hint">規則試玩支援「回家」「去咖啡館」「休息」等基本要求。AI 模式會自行選擇行動或回覆；單獨說的話只讓該角色知情。</p></form></section></aside></div>}
<footer className="bottom-note">QUIET HOURS <span>非小說正史的測試場景 · 規則模式使用固定範例，AI 模式才會產生模型決策</span></footer></main>;}
