'use client';
import { useEffect,useRef,useState } from 'react';
import { Moon,Play,Pause,SlidersHorizontal,MessageSquare,MapPin,Brain,Clock,Loader2,Eye,Radio,Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { locations,timeLabel,pendingInterventions,type World,type Character,type Action } from '@/lib/world';
import { currentUsage,defaultLimits,plannedCalls,type BudgetLimits } from '@/lib/activities';
import { habitViews } from '@/lib/habits';
import PixelWorld,{PixelSprite} from '@/components/pixel-world';
import type { EnvironmentView } from '@/lib/environment';
function Picker({value,onChange,items,label,disabled=false}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string;disabled?:boolean}){return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger className="picker" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>;}
function Initial({c,small=false}:{c:Character;small?:boolean}){return <span className={`initial ${small?'small':''}`} style={{color:c.color,borderColor:c.color+'55',background:c.color+'14'}}><PixelSprite id={c.id}/></span>;}
export default function WorldApp({signInPath,displayName,environment}:{signInPath:string;displayName:string;environment:EnvironmentView}){
const [world,setWorld]=useState<World|null>(null),[selected,setSelected]=useState('cass'),[busy,setBusy]=useState(false),[error,setError]=useState('');
const [mode,setMode]=useState('demo'),[key,setKey]=useState(''),[model,setModel]=useState(''),[settings,setSettings]=useState(false),[minutes,setMinutes]=useState('15'),[target,setTarget]=useState('cass'),[text,setText]=useState(''),[notice,setNotice]=useState(''),[signInRequired,setSignInRequired]=useState(false),[playing,setPlaying]=useState(false);
const [automatic,setAutomatic]=useState(false),[intervalSeconds,setIntervalSeconds]=useState('30'),[limits,setLimits]=useState<BudgetLimits>(defaultLimits);
const [directType,setDirectType]=useState<Action['type']>('rest'),[directTarget,setDirectTarget]=useState(''),[directContent,setDirectContent]=useState('');
const busyRef=useRef(false),autoRef=useRef(false),playingRef=useRef(false);
playingRef.current=playing;
function stopAuto(message?:string){autoRef.current=false;setAutomatic(false);if(message)setNotice(message);}
async function refresh(){if(busyRef.current)return;stopAuto();busyRef.current=true;setBusy(true);setError('');try{const r=await fetch('/api/world',{credentials:'same-origin'});const d=await r.json() as {world:World;error?:string;signInRequired?:boolean};if(!r.ok){if(r.status===401)setSignInRequired(true);throw Error(d.error);}setSignInRequired(false);setWorld(d.world);}catch(e){setError((e as Error).message);}finally{busyRef.current=false;setBusy(false);}}
useEffect(()=>{void refresh();},[]);
async function act(operation:string){if(busyRef.current||(operation==='advance'&&playingRef.current))return;busyRef.current=true;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/world',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation,minutes:Number(minutes),mode,key:mode!=='demo'?key:undefined,model:mode!=='demo'?model:undefined,target:['direct','takeover','return-control'].includes(operation)?'owner':target,text,limits,action:operation==='direct'?{type:directType,...(directTarget?{target:directTarget}:{}),...(directContent?{content:directContent}:{})}:undefined})});const d=await r.json() as {world:World;error?:string;signInRequired?:boolean;limitReached?:boolean};if(d.world)setWorld(d.world);if(!r.ok){if(r.status===401)setSignInRequired(true);throw Error(d.error);}setSignInRequired(false);if(d.limitReached)stopAuto();if(operation==='intervene')setText('');setNotice(d.limitReached?'已達用量上限，自動運行已暫停。':operation==='advance'?'回合已儲存':operation==='direct'?'店主的單次指定已儲存；下一回合優先執行。':operation==='takeover'?'已接管店主；沒有指定行動時會待命，其他角色繼續生活。':operation==='return-control'?'已交還控制權；下一回合由店主重新判斷意圖與行動。':`${target==='all'?'所有角色':world?.characters.find(c=>c.id===target)?.name||'角色'} 已收到；再推進一次時間，會做出行動或回覆。`);}catch(e){stopAuto();setError((e as Error).message);}finally{busyRef.current=false;setBusy(false);}}
useEffect(()=>{const onVisibility=()=>{if(document.visibilityState!=='visible'&&autoRef.current)stopAuto('分頁已離開前景，自動運行已暫停。');};document.addEventListener('visibilitychange',onVisibility);return ()=>document.removeEventListener('visibilitychange',onVisibility);},[]);
useEffect(()=>{if(!automatic||busy||playing||!world)return;const timer=setTimeout(()=>{if(autoRef.current&&document.visibilityState==='visible')void act('advance');},Number(intervalSeconds)*1000);return ()=>clearTimeout(timer);},[automatic,busy,playing,world,intervalSeconds,minutes,mode,key,model,limits]);
function selectCharacter(id:string){setSelected(id);setTarget(id);}
const character=world?.characters.find(c=>c.id===selected);
const directTargets=world&&character?(directType==='move'?locations.filter(l=>l.id!==character.location).map(l=>({value:l.id,label:l.name})):directType==='work'?[{value:'tea',label:'泡茶'},{value:'tidy',label:'整理桌面'},{value:'craft',label:'畫髮飾樣式'},{value:'craft-easy-challenge',label:'簡單設計挑戰（DC 8）'},{value:'craft-challenge',label:'設計挑戰（DC 12）'},{value:'craft-expert-challenge',label:'專家設計挑戰（DC 16）'},{value:'study-craft',label:'研究髮飾參考（限 Vera 房間）'}]:['say','persuade'].includes(directType)?[...(directType==='say'?[{value:'observer',label:'觀察者'}]:[]),...world.characters.filter(c=>c.id!==character.id&&c.location===character.location).map(c=>({value:c.id,label:c.name}))]:directType==='message'?world.characters.filter(c=>c.id!==character.id).map(c=>({value:c.id,label:c.name})):[]):[];
const pending=world&&character?pendingInterventions(world,character):[];
const habits=world&&character?habitViews(world,character).slice(0,5):[];
const usage=world?currentUsage(world):null;
const modelKey=mode==='demo'?'demo':`${mode}:${model}`;
const nextCalls=world&&mode!=='demo'?plannedCalls(world,Number(minutes),modelKey):0;
const canAdvance=!!world&&!busy&&!playing&&!signInRequired&&(mode==='demo'||!!(key.trim()&&model.trim()));
return <main><header className="topbar"><a href="/" className="brand"><span className="brand-mark"><Moon size={21}/></span><span>Quiet Hours<small>NPC 觀察室</small></span></a><div className="header-right"><span className="environment-badge" title="目前環境與建置的提交短碼">{environment.caption}</span><span className="edition">{displayName} · 已登入</span><form method="post" action="/api/auth/logout" onSubmit={()=>{stopAuto();setKey('');}}><Button variant="ghost" type="submit">登出</Button></form><Button variant="outline" className="settings-button" onClick={()=>setSettings(!settings)} aria-expanded={settings}><SlidersHorizontal size={16}/>模型設定</Button></div></header>
{settings&&<section className="settings panel"><div><h2>決策方式</h2><p>規則模式可以直接試玩。AI 先規劃活動，活動延續期間不再呼叫；新訊息或活動完成後重新規劃。OpenAI 直連使用你的 API 額度，與 ChatGPT 訂閱分開計費。</p></div><div className="settings-fields"><label>模式<Picker label="決策方式" value={mode} onChange={v=>{stopAuto();setMode(v);setKey('');setModel(v==='openai'?'gpt-6-luna':'');}} disabled={busy} items={[{value:'demo',label:'規則試玩'},{value:'openai',label:'OpenAI 直連'},{value:'ai',label:'OpenRouter AI'}]}/></label><label>模型{mode==='openai'?<Picker label="OpenAI 模型" value={model} onChange={v=>{stopAuto();setModel(v);}} disabled={busy} items={[{value:'gpt-6-luna',label:'GPT-6 Luna · 推薦'},{value:'gpt-6.1-sol',label:'GPT-6.1 Sol'}]}/>:<input value={model} onChange={e=>{stopAuto();setModel(e.target.value);}} placeholder="供應商／模型名稱" autoComplete="off" disabled={busy}/>}</label><label>{mode==='openai'?'OpenAI':'OpenRouter'} API Key<input type="password" value={key} onChange={e=>{stopAuto();setKey(e.target.value);}} placeholder="貼上你的 API Key" autoComplete="off"/></label></div><p className="settings-note">Key 僅保留在本次頁面記憶體，送到後端用於模型請求；不寫入世界紀錄。重新整理後需重填。<a href={mode==='openai'?'https://platform.openai.com/api-keys':'https://openrouter.ai/settings/keys'} target="_blank" rel="noreferrer">取得 API Key</a></p></section>}
<section className="world-toolbar"><div><div className="eyebrow">世界時間 · DAY {world?Math.floor(world.minute/1440)+1:'01'}</div><div className="clock">{world?timeLabel(world.minute):'21:00'}<span>夜色裡，生活繼續。</span></div></div><div className="advance"><span className={`mode-label ${mode!=='demo'?'ai':''}`}><Radio size={14}/>{mode==='openai'?'GPT 決策':mode==='ai'?'AI 決策':'規則試玩'}</span><Picker label="推進時間間隔" value={minutes} onChange={setMinutes} disabled={busy} items={[{value:'15',label:'15 分鐘'},{value:'30',label:'30 分鐘'}]}/><Button className="advance-button" disabled={!canAdvance||automatic} onClick={()=>act('advance')}>{busy?<Loader2 className="spin" size={17}/>:<Play size={16}/>} {busy?'處理中…':playing?'角色行動中…':'下一回合'}</Button></div></section>
<div className="feedback" aria-live="polite">{error?<div className="error" role="alert">{error}<Button variant="ghost" onClick={refresh} disabled={busy}>重新載入</Button>{signInRequired&&<a href={signInPath} target="_top" className="auth-retry">用 GitHub 重新登入</a>}</div>:notice?<span><Check size={14}/>{notice}</span>:<span>AI 規劃活動，程式延續活動。你可以手動推進，或開啟自動；離開分頁會暫停。</span>}</div>
{world&&<section className="automation panel" aria-label="自動運行與用量"><div className="automation-heading"><div><h2>{automatic?'自動運行中':'省 token 的活動模式'}</h2><p>{automatic?`每 ${intervalSeconds} 秒推進 ${minutes} 分鐘，等待角色行動完成後繼續。`:'按開始才會自動推進；離開分頁或發生錯誤時暫停。'}</p></div><Button className="auto-button" variant={automatic?'outline':'default'} disabled={!automatic&&!canAdvance} onClick={()=>{if(automatic)stopAuto('已暫停。正在處理的回合仍會完成。');else{autoRef.current=true;setAutomatic(true);setError('');setNotice(`已開始，約 ${intervalSeconds} 秒後推進下一回合。`);}}}>{automatic?<Pause size={16}/>:<Play size={16}/>} {automatic?'暫停自動':'開始自動'}</Button></div><div className="automation-fields"><label>推進速度<Picker label="自動推進速度" value={intervalSeconds} onChange={setIntervalSeconds} disabled={busy} items={[{value:'10',label:'每 10 秒'},{value:'30',label:'每 30 秒'},{value:'60',label:'每分鐘'}]}/></label><label>每小時 AI 呼叫上限<Picker label="每小時 AI 呼叫上限" value={String(limits.calls)} onChange={v=>setLimits({...limits,calls:Number(v)})} disabled={busy} items={[3,6,12,24,48,120].map(v=>({value:String(v),label:`${v} 次`}))}/></label><label>每小時 token 停止門檻<Picker label="每小時 token 停止門檻" value={String(limits.tokens)} onChange={v=>setLimits({...limits,tokens:Number(v)})} disabled={busy} items={[1000,10000,30000,60000,120000,500000].map(v=>({value:String(v),label:v.toLocaleString()}))}/></label></div>{usage&&<><div className="usage-grid"><div><span>本小時 AI 呼叫</span><strong>{usage.calls} <small>/ {limits.calls}</small></strong></div><div><span>已回報 token</span><strong>{(usage.inputTokens+usage.outputTokens).toLocaleString()} <small>/ {limits.tokens.toLocaleString()}</small></strong></div><div><span>延續活動省下的決策</span><strong>{usage.savedDecisions} <small>次</small></strong></div><div><span>下一回合預計詢問</span><strong>{nextCalls} <small>名角色</small></strong></div></div><p className="usage-note">輸入 {usage.inputTokens.toLocaleString()} · 輸出 {usage.outputTokens.toLocaleString()} · 累計 {usage.totalCalls} 次 AI 呼叫。{usage.unknownCalls>0?`另有 ${usage.unknownCalls} 次未收到供應商用量。`:''} 到達門檻後停止新請求，單次回覆可能超過 token 門檻。規則試玩不使用 API。</p></>}</section>}
{!world?<section className="panel loading"><Loader2 className={busy?'spin':''}/><p>{busy?'正在讀取你的世界…':'世界尚未載入'}</p></section>:<div className="workspace"><div className="main-column"><section className="world-view panel"><div className="section-head"><h1>此刻的世界</h1><span><Eye size={15}/>觀察者視角</span></div><PixelWorld world={world} selected={selected} onSelect={selectCharacter} onPlayingChange={setPlaying}/><div className="world-footer"><span>{world.characters.length} 個角色 · {locations.length} 個地點</span><span><Clock size={14}/>已走過 {world.turn} 個回合</span></div></section>
<section className="feed panel"><div className="section-head"><h2>生活紀錄</h2><span>最近 300 則 · 由新到舊</span></div><div className="event-list">{[...world.events].reverse().map(event=>{const c=world.characters.find(x=>x.id===event.actor);return <article className="event" key={event.id}><time><small>D{Math.floor(event.time/1440)+1}</small>{timeLabel(event.time)}</time><span className="event-marker" style={{background:c?.color||'#98a4b7'}}/><div><div className="event-meta"><b style={{color:c?.color}}>{c?.name||(event.actor==='observer'?'觀察者':'世界')}</b><span>{event.kind==='say'&&event.scene?.target==='observer'?'回覆你':event.kind==='reflect'?'私密想法':event.kind==='message'?'私人訊息':event.kind==='attempt'?'D20 判定':event.kind==='blocked'?'規則攔截':event.kind==='intervention'?'介入事件':'生活片段'}</span></div><p>{event.text}</p>{event.resolution&&<small>🎲 D20 {event.resolution.roll} {event.resolution.modifier>=0?"+":""}{event.resolution.modifier} − DC {event.resolution.dc} = {event.resolution.total} · {({"critical-success":"大成功",success:"成功",mixed:"部分成功",failure:"失敗","critical-failure":"大失敗"})[event.resolution.outcome]}</small>}<small className="audience">知情：{event.audience.map(id=>world.characters.find(x=>x.id===id)?.name).join('、')||'無'}</small></div></article>})}</div></section></div>
<aside className="side-column"><section className="character panel"><div className="section-head"><h2>角色狀態</h2><Brain size={17}/></div><div className="character-picker">{world.characters.map(c=><button key={c.id} onClick={()=>selectCharacter(c.id)} className={selected===c.id?'active':''} aria-pressed={selected===c.id}>{c.name}</button>)}</div>{character&&<><div className="identity"><Initial c={character}/><div><h2>{character.name}</h2><span><MapPin size={13}/>{locations.find(l=>l.id===character.location)?.name}</span></div><span className="mood" style={{color:character.color}}>{character.mood}</span></div><p className="activity">{character.activity}</p>{character.plan&&character.plan.until>world.minute&&<div className="activity-plan"><Clock size={14}/><span>活動延續中 · 約剩 {character.plan.until-world.minute} 分鐘<br/>{character.control?.active?'指定活動由你控制':'收到新對話時會重新決策'}</span></div>}{pending.length>0&&<div className="pending-request"><h3>等待下一回合回應</h3><p>{pending.at(-1)?.text}</p></div>}<div className="detail"><h3>現在想做的事</h3><p>{character.goal}</p></div><div className="detail"><h3>意圖佇列 <span>由角色安排順序</span></h3>{character.intents?.length?<ol className="intent-list">{character.intents.map(intent=><li key={intent.id}><p>{intent.content}</p><small>強度：{({low:'低',medium:'中',high:'高'})[intent.intensity]} · 重要：{({low:'低',medium:'中',high:'高'})[intent.importance]} · 急迫：{({low:'低',medium:'中',high:'高'})[intent.urgency]}</small>{intent.context&&<p className="hint">{intent.context}</p>}</li>)}</ol>:<p className="hint">目前沒有保留的意圖。AI 決策時會自行形成與調整。</p>}</div><div className="detail"><h3>設計成果 <span>最近 {character.projects?.length||0} 份</span></h3>{character.projects?.length?<div className="memories">{[...character.projects].reverse().slice(0,5).map(item=><div key={item.resultId}><p>{item.theme} · {({'finished-with-variation':'完成＋額外收穫',finished:'完成',draft:'初稿仍需調整',unfinished:'尚未完成',spoiled:'草稿受損'})[item.status]}</p><small>DC {item.dc}</small></div>)}</div>:<p className="hint">尚無需 D20 判定的設計成果。</p>}</div>
<div className="detail"><h3>性格</h3><p>{character.personality}</p>{character.abilityTags?.length?<p className="hint">能力特質：{character.abilityTags.join('、')}</p>:null}</div><div className="detail relations"><h3>關係</h3>{Object.entries(character.relationships).map(([id,t])=><p key={id}><b>{world.characters.find(x=>x.id===id)?.name}</b>{t}</p>)}</div><div className="detail habit-detail"><h3>生活習慣 <span>從自主選擇累積</span></h3>{habits.length?<div className="habit-list">{habits.map(habit=><article key={habit.key}><div><span className={`habit-stage ${habit.established?'established':''}`}>{habit.fading?'正在淡化':habit.established?'已形成':'形成中'}</span><small>{habit.days} 個世界日出現</small></div><p>{habit.label}</p><small>最近出現：D{Math.floor(habit.lastSeen/1440)+1} · {timeLabel(habit.lastSeen)}</small></article>)}</div>:<p className="habit-empty">還在認識自己的生活節奏。AI 自主行動在不同世界日重複出現後，會逐漸累積習慣。</p>}<p className="habit-note">三個不同世界日出現後形成；久未出現會變淡。AI 可改變主意。規則試玩、活動延續與回應你的要求不計入。</p></div><div className="detail"><h3>自己的記憶 <span>{character.memories.length} / 80</span></h3><div className="memories">{[...character.memories].reverse().map((m,i)=><div key={`${m.time}-${i}`}><time>D{Math.floor(m.time/1440)+1} · {timeLabel(m.time)}</time><p>{m.text}</p></div>)}</div></div></>}</section>
{character?.id==='owner'&&<section className="intervene panel" aria-label="店主直接控制"><div className="section-head"><h2>店主直接控制</h2><Brain size={17}/></div><p className="hint">{character.control?.mode==='taken-over'?'由你暫時控制。'+(character.control?.pending?'已保存指定，等待下一回合。':character.control?.active?'正在執行指定活動；完成後待命。':'店主待命，其他角色繼續生活。'):character.control?.pending?'已保存單次指定，等待下一回合。':character.control?.active?'正在執行指定活動；完成後恢復自主生活。':'目前自主生活。單次指定會優先取代下一個活動，保留意圖。'}</p><Button type="button" variant="outline" disabled={busy||playing||signInRequired} onClick={()=>void act(character.control?.mode==='taken-over'?'return-control':'takeover')}>{character.control?.mode==='taken-over'?'交還控制權':'暫時接管店主'}</Button>{character.control?.mode==='taken-over'&&<p className="hint">交還會結束指定活動、取消尚未執行的指定；保留意圖與實際經歷，下回合重新自主判斷。</p>}<form onSubmit={e=>{e.preventDefault();void act('direct');}}><label>指定行動<Picker label="店主指定行動" value={directType} onChange={v=>{setDirectType(v as Action['type']);setDirectTarget('');setDirectContent('');}} disabled={busy||playing} items={[{value:'rest',label:'休息'},{value:'observe',label:'觀察周圍'},{value:'work',label:'工作'},{value:'move',label:'移動'},{value:'say',label:'說話'},{value:'persuade',label:'說服（D20）'},{value:'message',label:'傳訊息'},{value:'reflect',label:'思考'}]}/></label>{directTargets.length>0&&<label>對象／工作<Picker label="店主行動對象" value={directTarget} onChange={setDirectTarget} disabled={busy||playing} items={directTargets}/></label>}{['say','persuade','message','reflect'].includes(directType)&&<><label htmlFor="direct-content">指定內容</label><textarea id="direct-content" value={directContent} onChange={e=>setDirectContent(e.target.value)} maxLength={500} rows={3}/></>}<Button type="submit" variant="outline" disabled={busy||playing||signInRequired||(directTargets.length>0&&!directTargets.some(t=>t.value===directTarget))||(['say','persuade','message','reflect'].includes(directType)&&!directContent.trim())}>單次指定下一行動</Button><p className="hint">這是直接選定店主行動。休息、工作、觀察及思考持續約 60 分鐘；一般介入仍讓 NPC 自行判斷。</p></form></section>}
<section className="intervene panel"><div className="section-head"><h2>輕輕介入</h2><MessageSquare size={17}/></div><form onSubmit={e=>{e.preventDefault();void act('intervene');}}><label>誰會知道？<Picker label="事件知情對象" value={target} onChange={setTarget} disabled={busy} items={[...world.characters.map(c=>({value:c.id,label:`只對 ${c.name} 說`})),{value:'all',label:'所有人的共同事件'}]}/></label><label htmlFor="intervention">你想說的話或發生的事</label><textarea id="intervention" value={text} onChange={e=>setText(e.target.value)} placeholder="例如：咖啡館明天下午有一場小型手作活動。" maxLength={500} rows={3}/><div className="intervene-bottom"><span>{text.length} / 500</span><Button type="submit" variant="outline" disabled={busy||playing||!text.trim()}>加入事件</Button></div><p className="hint">規則試玩支援「回家」「去咖啡館」「休息」等基本要求。AI 模式會自行選擇行動或回覆；單獨說的話只讓該角色知情。</p></form></section></aside></div>}
<footer className="bottom-note">QUIET HOURS <span>非小說正史的測試場景 · 規則模式使用固定範例，AI 模式才會產生模型決策</span><span>{environment.caption}</span></footer></main>;}
